name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

- name: Build and Deploy
  run: |
    git config --global user.name 'GitHub Actions'
    git config --global user.email 'actions@github.com'
    npm install -g @angular/cli
    npm install
    ng build --prod --base-href="/printed-waistband-gripper-tape/"
    cp -R dist/printed-waistband-gripper-tape/* .
    echo "printed-waistband-gripper-tape.com" > CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
